# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_campus
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# Google Client ID
google.client.id=85956272758-lqcmjrtkistskdbs6j0no8mvq22e58v1.apps.googleusercontent.com


jwt.secret=SmartCampusBookingSystemSecretKeyForJWTGeneration2026